AmbireTech/adex-protocol-eth

contracts/extra/Identity.sol
js/IdentityDeploy.js
test/TestIdentity.js

implements opening a channel through a routine authorization, as long as the validators are whitelisted in a primitive registry

Enhancement/channel-open; fix #30

---

contracts/Identity.sol
contracts/libs/ChannelLibrary.sol
js/Identity.js
js/IdentityProxyDeploy.js
package.json
test/TestIdentity.js
test/mocks/Token.sol

this PR adds recurring fees to RoutineAuthorizations, by simply changing the fee to be weekly
this additionally incentivizes the relayer to peform their duties
additionally, if the relayer does not perform, an authorization can always be revoked

RoutineAuthorizations: recurring fees

---

contracts/libs/ChannelLibrary.sol
test/TestAdExCore.js

ChannelLibrary: always require that the leading validator signed

---

contracts/ADXToken.sol
contracts/AdExCore.sol
contracts/AdExENSRegistrar.sol
contracts/Identity.sol
contracts/IdentityFactory.sol
contracts/Migrations.sol
contracts/Staking.sol
contracts/libs/ChannelLibrary.sol
contracts/libs/MerkleProof.sol
contracts/libs/SafeERC20.sol
contracts/libs/SafeMath.sol
contracts/libs/SignatureValidator.sol
package-lock.json
package.json
truffle-config.js

Fixes issue #98 . Upgrades core contracts to Solidity 0.6.12

Upgrade contracts to Solidity v0.6.12

---

contracts/ADXToken.sol
contracts/AdExCore.sol
contracts/AdExENSRegistrar.sol
contracts/Identity.sol
contracts/IdentityFactory.sol
contracts/Migrations.sol
contracts/Staking.sol
contracts/libs/ChannelLibrary.sol
contracts/libs/MerkleProof.sol
contracts/libs/SafeERC20.sol
contracts/libs/SafeMath.sol
contracts/libs/SignatureValidator.sol
package-lock.json
package.json
test/TestSafeERC20.sol
test/mocks/BadToken.sol
test/mocks/Libs.sol
test/mocks/Token.sol
test/mocks/WorstToken.sol
truffle-config.js

Upgrade contracts

---

contracts/ADXToken.sol

minor changes

---

contracts/StakingPool.sol
contracts/SupplyController.sol
contracts/interfaces/IADXToken.sol
test/TestADXToken.js
test/TestLoyaltyPool.js

- Change `resetLimit()` in StakingPool to an internal function
- Remove hardcoded `ADXToken` address in `SupplyController`

SupplyController, StakingPool 

---

contracts/Identity.sol
contracts/IdentityFactory.sol
js/IdentityProxyDeploy.js
package-lock.json
package.json

Fixed Identity ability to receive ETH

Identity receive eth fix

---

contracts/wallet/Zapper.sol

added optional wrap to lending with Zapper `tradeV3Single` function

Zapper:  tradeV3Single optional lending wrap

---

README.md
migrations/1_initial_migration.js
package-lock.json
package.json
truffle-config.js

Final touches for https://github.com/AdExNetwork/adex-protocol-eth/issues/145

Wallet deploy

---

README.md
js/Bundle.js

Added moonbeam chain

---

js/Bundle.js

- added moonriver to bundle.js

added moonriver to bundle.js

---

js/Bundle.js

We need this property to store unstoppable domains address Label in transactions

Added meta property to bundle

---

js/Bundle.js

added new networks in bundle.js: 
* gnosis
* kucoin
* andromeda
* cronos
* aurora

new networks in bundle.js

---

js/Bundle.js

Added rinkeby & optimism chains in Bundle.js

Added rinkeby & optimism chains

---

js/Bundle.js

- added gasTank prop in submit method

added gasTank prop in submit method

---

js/Bundle.js

- fix gasTank param in Bundle.js

fix gasTank param in Bundle.js

---

js/MerkleTree.js
package-lock.json

added second params in MerkleTree constructor for optional deduplicate

deduplicate-in-MerkleTree-optiona

---

js/Bundle.js

Feature / Mumbai test network

---

audits/forkway-loyalty-pool.md

fix typo forkway-loyalty-pool.md
